/**
 * Agent 5: GitHub Publisher + Azure Container Apps Deployer
 *
 * Creates a real GitHub repo, commits all generated code,
 * and deploys as an ephemeral Azure Container App.
 */

import { Octokit } from '@octokit/rest';
import { execSync } from 'child_process';

const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const GITHUB_ORG = process.env.GITHUB_ORG || '';
const ACR_LOGIN_SERVER = process.env.ACR_LOGIN_SERVER;
const ACR_USERNAME = process.env.ACR_USERNAME;
const ACR_PASSWORD = process.env.ACR_PASSWORD;
const ACA_RESOURCE_GROUP = process.env.ACA_RESOURCE_GROUP;
const ACA_ENVIRONMENT = process.env.ACA_ENVIRONMENT;

function generateDockerfile(hasReact, hasVue) {
  const stages = [];

  if (hasReact) {
    stages.push(`FROM node:20-alpine AS build-react
WORKDIR /app/react
COPY react/package*.json ./
RUN npm install
COPY react/ ./
RUN npm run build`);
  }

  if (hasVue) {
    stages.push(`FROM node:20-alpine AS build-vue
WORKDIR /app/vue
COPY vue/package*.json ./
RUN npm install
COPY vue/ ./
RUN npm run build`);
  }

  let copies = '';
  if (hasReact) copies += '\nCOPY --from=build-react /app/react/dist /usr/share/nginx/html/react';
  if (hasVue) copies += '\nCOPY --from=build-vue /app/vue/dist /usr/share/nginx/html/vue';

  return `${stages.join('\n\n')}

FROM nginx:alpine
RUN echo 'server { listen 80; root /usr/share/nginx/html; index index.html; location /react/ { try_files $uri $uri/ /react/index.html; } location /vue/ { try_files $uri $uri/ /vue/index.html; } location /docs/ { autoindex on; } location / { try_files $uri /index.html; } }' > /etc/nginx/conf.d/default.conf${copies}
COPY docs/ /usr/share/nginx/html/docs/
COPY public/index.html /usr/share/nginx/html/index.html
EXPOSE 80`;
}

function generateLandingPage(projectName) {
  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>${projectName} — Prototype</title>
<style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Segoe UI',sans-serif;background:linear-gradient(135deg,#667eea,#764ba2);min-height:100vh;display:flex;align-items:center;justify-content:center;padding:20px}.c{background:#fff;border-radius:16px;padding:60px 40px;max-width:800px;width:100%;box-shadow:0 20px 60px rgba(0,0,0,.3);text-align:center}h1{font-size:2.5rem;margin-bottom:10px;color:#333}.s{color:#666;margin-bottom:40px}.l{display:flex;gap:20px;justify-content:center;flex-wrap:wrap}.l a{padding:20px 40px;background:#0078D4;color:#fff;text-decoration:none;border-radius:8px;font-size:1.2rem;font-weight:600;transition:.3s}.l a:hover{background:#005A9E;transform:translateY(-2px)}.b{display:inline-block;background:#28a745;color:#fff;padding:5px 15px;border-radius:20px;font-size:.85rem;margin-bottom:20px}.d{margin-top:40px}.d a{color:#0078D4;text-decoration:none}</style>
</head><body><div class="c"><div class="b">Generated by Foundry Agents</div><h1>${projectName}</h1><p class="s">Choose your preferred framework</p><div class="l"><a href="./react/">React</a><a href="./vue/">Vue</a></div><div class="d"><a href="./docs/">Documentation</a></div></div></body></html>`;
}

export async function runAgent5({ requirements, code, docs, repoName, visibility, collaborators, ttlHours }) {
  if (!GITHUB_TOKEN) throw Object.assign(new Error('GITHUB_TOKEN not configured'), { stage: 'agent5-publish' });

  const octokit = new Octokit({ auth: GITHUB_TOKEN });
  const projectName = repoName || requirements.project_metadata?.name || 'prototype';

  // 1. Create GitHub repo
  console.log('    Creating GitHub repo...');
  let repo;
  try {
    if (GITHUB_ORG) {
      const { data } = await octokit.repos.createInOrg({
        org: GITHUB_ORG,
        name: projectName,
        description: `Prototype generated by Foundry Prototype Generator — ${requirements.project_metadata?.description || ''}`,
        private: visibility === 'private',
        auto_init: true,
      });
      repo = data;
    } else {
      const { data } = await octokit.repos.createForAuthenticatedUser({
        name: projectName,
        description: `Prototype generated by Foundry Prototype Generator`,
        private: visibility === 'private',
        auto_init: true,
      });
      repo = data;
    }
  } catch (err) {
    if (err.status === 422) {
      // Repo already exists — get it
      const owner = GITHUB_ORG || (await octokit.users.getAuthenticated()).data.login;
      const { data } = await octokit.repos.get({ owner, repo: projectName });
      repo = data;
      console.log('    Repo already exists, reusing...');
    } else {
      throw Object.assign(err, { stage: 'agent5-publish' });
    }
  }

  const owner = repo.owner.login;

  // 2. Commit all files
  console.log('    Committing files...');
  const allFiles = {};

  // React files
  const reactFiles = code.react_project?.files || {};
  for (const [path, content] of Object.entries(reactFiles)) {
    allFiles[`react/${path}`] = content;
  }

  // Vue files  
  const vueFiles = code.vue_project?.files || {};
  for (const [path, content] of Object.entries(vueFiles)) {
    allFiles[`vue/${path}`] = content;
  }

  // Docs
  if (docs.readme) allFiles['README.md'] = docs.readme;
  if (docs.architecture) allFiles['docs/ARCHITECTURE.md'] = docs.architecture;
  if (docs.components) allFiles['docs/COMPONENTS.md'] = docs.components;
  if (docs.deployment) allFiles['docs/DEPLOYMENT.md'] = docs.deployment;

  // Generated files
  const hasReact = Object.keys(reactFiles).length > 0;
  const hasVue = Object.keys(vueFiles).length > 0;
  allFiles['Dockerfile'] = generateDockerfile(hasReact, hasVue);
  allFiles['public/index.html'] = generateLandingPage(projectName);
  allFiles['.gitignore'] = 'node_modules/\ndist/\n.env\n';

  // Commit each file via GitHub API
  for (const [filePath, content] of Object.entries(allFiles)) {
    try {
      // Check if file exists
      let sha;
      try {
        const { data: existing } = await octokit.repos.getContent({ owner, repo: projectName, path: filePath });
        sha = existing.sha;
      } catch { /* file doesn't exist */ }

      await octokit.repos.createOrUpdateFileContents({
        owner,
        repo: projectName,
        path: filePath,
        message: `Add ${filePath}`,
        content: Buffer.from(typeof content === 'string' ? content : JSON.stringify(content, null, 2)).toString('base64'),
        ...(sha ? { sha } : {}),
      });
    } catch (err) {
      console.warn(`    Warning: Failed to commit ${filePath}: ${err.message}`);
    }
  }

  // 3. Add collaborators
  for (const username of collaborators) {
    try {
      await octokit.repos.addCollaborator({ owner, repo: projectName, username, permission: 'push' });
    } catch { /* ignore */ }
  }

  // 4. Build and deploy to Azure Container Apps
  let prototypeUrl = `${repo.html_url}`;
  let reactUrl = prototypeUrl;
  let vueUrl = prototypeUrl;

  if (ACR_LOGIN_SERVER && ACA_RESOURCE_GROUP && ACA_ENVIRONMENT) {
    console.log('    Building Docker image...');
    try {
      // Clone the repo, build, push, deploy
      const tmpDir = `/tmp/fpg-${projectName}-${Date.now()}`;
      execSync(`git clone --depth 1 https://x-access-token:${GITHUB_TOKEN}@github.com/${owner}/${projectName}.git ${tmpDir}`, { stdio: 'pipe' });

      const imageTag = `${ACR_LOGIN_SERVER}/prototypes/${projectName}:latest`;

      execSync(`docker build --platform linux/amd64 -t ${imageTag} ${tmpDir}`, {
        stdio: 'pipe',
        timeout: 300000,
      });

      console.log('    Pushing to ACR...');
      execSync(`docker push ${imageTag}`, { stdio: 'pipe', timeout: 120000 });

      console.log('    Deploying to Azure Container Apps...');
      const appName = projectName.toLowerCase().replace(/[^a-z0-9-]/g, '-').slice(0, 32);
      const createdAt = new Date().toISOString();

      // Try create, fall back to update
      try {
        execSync(`az containerapp create \
          --name ${appName} \
          --resource-group ${ACA_RESOURCE_GROUP} \
          --environment ${ACA_ENVIRONMENT} \
          --image ${imageTag} \
          --registry-server ${ACR_LOGIN_SERVER} \
          --registry-username ${ACR_USERNAME} \
          --registry-password "${ACR_PASSWORD}" \
          --target-port 80 \
          --ingress external \
          --min-replicas 0 --max-replicas 1 \
          --cpu 0.25 --memory 0.5Gi \
          --tags "created-at=${createdAt}" "ttl=${ttlHours}" "project=${projectName}" "created-by=foundry-prototype-generator"`,
          { stdio: 'pipe', timeout: 120000 });
      } catch {
        execSync(`az containerapp update \
          --name ${appName} \
          --resource-group ${ACA_RESOURCE_GROUP} \
          --image ${imageTag}`,
          { stdio: 'pipe', timeout: 60000 });
      }

      const fqdn = execSync(
        `az containerapp show --name ${appName} --resource-group ${ACA_RESOURCE_GROUP} --query "properties.configuration.ingress.fqdn" -o tsv`,
        { encoding: 'utf8', timeout: 15000 },
      ).trim();

      prototypeUrl = `https://${fqdn}`;
      reactUrl = `https://${fqdn}/react/`;
      vueUrl = `https://${fqdn}/vue/`;

      // Cleanup tmp
      execSync(`rm -rf ${tmpDir}`, { stdio: 'pipe' });

    } catch (deployErr) {
      console.error('    ACA deploy failed:', deployErr.message);
      // Fall back to GitHub repo URL
    }
  } else {
    console.log('    Skipping ACA deploy (Azure not configured)');
  }

  const expiresAt = new Date(Date.now() + ttlHours * 3600000).toISOString();

  return {
    repository_url: repo.html_url,
    prototype_url: prototypeUrl,
    react_url: reactUrl,
    vue_url: vueUrl,
    actions_url: `${repo.html_url}/actions`,
    expires_at: expiresAt,
    ttl_hours: ttlHours,
  };
}
