/**
 * Agent 4: Documentation Writer
 * Generates README.md and documentation files.
 */

import { callLLMJson } from '../llm.js';

const SYSTEM_PROMPT = `You are a technical writer specializing in software documentation.

Generate documentation for a prototype project.

Output ONLY valid JSON:
{
  "readme": "# Project Name\\n\\nFull README.md content with Quick Start, structure, scripts...",
  "architecture": "# Architecture\\n\\nArchitectural decisions, data flow, Mermaid diagrams...",
  "components": "# Components\\n\\nList of design system components used, props, examples...",
  "deployment": "# Deployment\\n\\nHow the deploy works, environment variables, access URLs..."
}

Rules:
- Write in English
- Use proper Markdown with headers, code blocks, tables
- Include a Mermaid diagram in the architecture doc
- README must include Quick Start for both React and Vue
- Include npm scripts (dev, build, preview)
- Mention this was generated by Foundry Prototype Generator
- Keep content practical and specific to the actual project`;

export async function runAgent4(requirements, components, code) {
  try {
    const input = {
      requirements,
      components_used: components.selected_components?.map((c) => c.name) || [],
      frameworks: requirements.project_metadata?.frameworks || ['react', 'vue'],
      project_name: requirements.project_metadata?.name || 'prototype',
    };
    return await callLLMJson(
      SYSTEM_PROMPT,
      JSON.stringify(input, null, 2),
      { temperature: 0.3, maxTokens: 4000 },
    );
  } catch (error) {
    error.stage = 'agent4-docs';
    throw error;
  }
}
